[[ImageArticle-API]]
== ImageArticle API

[[ImageArticle-목록조회-API]]
=== ImageArticle 목록조회 API(좋아요 순)
operation::ImageArticleTest/listHotImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 목록조회 API(무작위)
operation::ImageArticleTest/listRandomImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 목록조회 API(최신)
operation::ImageArticleTest/listRecentImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 목록조회 API(태그)
operation::ImageArticleTest/listTagImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 목록조회 API(무작위 태그)
operation::ImageArticleTest/listRandomTagImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']


[[ImageArticle-상세조회-API]]
=== ImageArticle 상세조회 API
operation::ImageArticleTest/detailImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 상세조회 API(존재하지 않는 게시글 접근할 때)
operation::ImageArticleTest/detailNonImageArticleFailTest[/snippets='http-request,request-headers,path-parameters,http-response']

[[ImageArticle-작성-API]]
=== ImageArticle 작성 API
operation::ImageArticleTest/writeImageArticleSuccessTest[/snippets='http-request,request-headers,request-fields,http-response']

=== ImageArticle 작성 API(이미지가 없을 때, 비정상)
operation::ImageArticleTest/writeImageArticleFailTest[/snippets='http-request,request-headers,request-fields,http-response']

[[ImageArticle-삭제-API]]
=== ImageArticle 삭제 API(게시글만 삭제)
operation::ImageArticleTest/deleteOnlyImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 삭제 API(잘못된 사용자 접근할 때)
operation::ImageArticleTest/detailNonImageArticleFailTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 삭제 API(게시글, 이미지 모두 삭제)
operation::ImageArticleTest/deleteImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']

=== ImageArticle 삭제 API(잘못된 사용자 접근할 때)
operation::ImageArticleTest/deleteWrongUserImageArticleSuccessTest[/snippets='http-request,request-headers,path-parameters,http-response']


