[[Notice-API]]
== Notice API


[[Notice-작성-API]]
=== Notice 작성 API
operation::NoticeIntegrationTest/writeNoticeArticleSuccessTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Notice 작성 API(일반 사용자 시도 시)
operation::NoticeIntegrationTest/writeNoticeArticleAuthFailTest[snippets='http-request,request-headers,request-fields,http-response']

=== Notice 작성 API(글이 짧을 경우)
operation::NoticeIntegrationTest/writeNoticeArticleLowerSubjectFailTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Notice 수정 API
operation::NoticeIntegrationTest/modifyNoticeArticleSuccessTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Notice 수정 API(일반 사용자 시도 시)
operation::NoticeIntegrationTest/modifyNoticeArticleAuthFailTest[snippets='http-request,request-headers,request-fields,http-response']

=== Notice 수정 API(글이 짧을 경우)
operation::NoticeIntegrationTest/modifyNoticeArticleLowerSubjectFailTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== Notice 수정 API(없는 번호인 경우)
operation::NoticeIntegrationTest/modifyNoticeArticleNotExistsIdFailTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']
