[[방-API]]
== 방 API

[[방-정보-조회-API]]
=== 방 정보 조회 테스트(정상) API
operation::RoomIntegrationTest/readRoomInfoSuccessTest[snippets='http-request,request-headers,request-parameters,http-response,response-fields']


[[방-확인-API]]
=== 방 연결 확인 테스트(정상, 회원) API
operation::RoomIntegrationTest/checkRoomConnectionMemberSuccessTest[snippets='http-request,request-headers,http-response']

=== 방 연결 확인 테스트(비정상, 회원) API
operation::RoomIntegrationTest/checkRoomConnectionMemberFailTest[snippets='http-request,request-headers,http-response']

=== 방 연결 확인 테스트(정상, AccessToken 있는 비회원) API
operation::RoomIntegrationTest/checkRoomConnectionGuestSuccessTest[snippets='http-request,request-headers,http-response']

=== 방 연결 확인 테스트(정상, AccessToken 없는 비회원) API
operation::RoomIntegrationTest/checkRoomConnectionNonAccessGuestSuccessTest[snippets='http-request,http-response']

=== 방 연결 확인 테스트(비정상, AccessToken 있는 비회원) API
operation::RoomIntegrationTest/checkRoomConnectionGuestSuccessTest[snippets='http-request,request-headers,http-response']

=== 방 비밀번호 확인 테스트(정상) API
operation::RoomIntegrationTest/checkRoomPasswordSuccessTest[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 방 비밀번호 틀렸을 때 테스트(비정상) API
operation::RoomIntegrationTest/checkRoomNotEqPasswordFailTest[snippets='http-request,request-headers,request-fields,http-response']

=== 잘못된 방 코드 접근 테스트(비정상) API
operation::RoomIntegrationTest/checkRoomNotCodePasswordFailTest[snippets='http-request,request-headers,request-fields,http-response']


[[방-작성-API]]
=== 방 생성(정상) API
operation::RoomIntegrationTest/createRoomSuccessTest[snippets='http-request,request-headers,request-fields,http-response']

[[방-정보변경-API]]
=== 방 시작여부 변경 테스트(정상) API
operation::RoomIntegrationTest/updateRoomStartYnSuccessTest[snippets='http-request,request-headers,path-parameters,http-response']

[[방-삭제-API]]
=== 방 삭제(정상) API
operation::RoomIntegrationTest/deleteRoomSuccessTest[snippets='http-request,request-headers,http-response']
